baseURL: https://asubedi.com.np/

languageCode: en-us
defaultContentLanguage: en
title: Ashish's Site
theme: cupper-hugo-theme
enableGitInfo: true

taxonomies:
  tag: Ashish Subedi

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  regularPages: 3
  description: Personal Website of Ashish Subedi. Contains some blogs and random stuffs that come along the way.
  homeMetaContent: Personal Website of Ashish Subedi. Contains some blogs and random stuffs that come along the way.
  footer: :)
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: darkVapour
  katex: true
  hideHeaderLinks: true
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: true
  navTitleText: Ashish's Site
  logoAlt: Ashish's Site

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /blog/
      weight: 2
    - name: About
      url: /about/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
